# Generated by Django 5.2.5 on 2025-08-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_id_alter_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
    ]
